// Caractéristiques techniques officielles par modèle d'iPhone.
//
// Source des valeurs : fiches techniques publiques Apple. Mettre "À confirmer"
// quand on n'a pas de certitude — le composant le rend en italique gris pour
// signaler au client qu'on n'invente rien.
//
// La clé de l'objet DOIT correspondre exactement à `products.model` en base
// (la même chaîne que `catalogue-source.js`). Si le modèle d'un produit
// affiché n'est pas listé ici, getIphoneSpecs() renvoie null et le composant
// masque proprement le bloc — pas de section vide à l'écran.

export interface IphoneSpec {
  annee: number;
  ecran: string;
  puce: string;
  photo: string;
  selfie: string;
  video: string;
  autonomie: string;
  connectique: string;
  reseau: '4G' | '5G';
  resistance: string;
  poids: string;
}

const SPECS: Record<string, IphoneSpec> = {
  // ── 2016 ──────────────────────────────────────────────────────────────
  'iPhone 7': {
    annee: 2016,
    ecran: '4,7" Retina HD (1334 × 750)',
    puce: 'Apple A10 Fusion',
    photo: '12 Mpx grand-angle f/1.8',
    selfie: '7 Mpx FaceTime HD',
    video: '4K à 30 i/s',
    autonomie: "Jusqu'à 13h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '138 g',
  },
  'iPhone 7 Plus': {
    annee: 2016,
    ecran: '5,5" Retina HD (1920 × 1080)',
    puce: 'Apple A10 Fusion',
    photo: 'Double 12 Mpx (grand-angle f/1.8 + téléobjectif f/2.8, zoom 2x)',
    selfie: '7 Mpx FaceTime HD',
    video: '4K à 30 i/s',
    autonomie: "Jusqu'à 14h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '188 g',
  },

  // ── 2017 ──────────────────────────────────────────────────────────────
  'iPhone 8': {
    annee: 2017,
    ecran: '4,7" Retina HD',
    puce: 'Apple A11 Bionic',
    photo: '12 Mpx grand-angle f/1.8',
    selfie: '7 Mpx FaceTime HD',
    video: '4K jusqu\'à 60 i/s',
    autonomie: "Jusqu'à 13h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '148 g',
  },
  'iPhone 8 Plus': {
    annee: 2017,
    ecran: '5,5" Retina HD',
    puce: 'Apple A11 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.8 + téléobjectif f/2.8, zoom 2x)',
    selfie: '7 Mpx FaceTime HD',
    video: '4K jusqu\'à 60 i/s',
    autonomie: "Jusqu'à 14h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '202 g',
  },
  'iPhone X': {
    annee: 2017,
    ecran: '5,8" Super Retina OLED (2436 × 1125)',
    puce: 'Apple A11 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.8 + téléobjectif f/2.4, zoom 2x)',
    selfie: '7 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s',
    autonomie: "Jusqu'à 13h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '174 g',
  },

  // ── 2018 ──────────────────────────────────────────────────────────────
  'iPhone XR': {
    annee: 2018,
    ecran: '6,1" Liquid Retina LCD',
    puce: 'Apple A12 Bionic',
    photo: '12 Mpx grand-angle f/1.8',
    selfie: '7 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, stéréo',
    autonomie: "Jusqu'à 16h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '194 g',
  },
  'iPhone XS': {
    annee: 2018,
    ecran: '5,8" Super Retina OLED HDR',
    puce: 'Apple A12 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.8 + téléobjectif f/2.4, zoom 2x)',
    selfie: '7 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, stéréo',
    autonomie: "Jusqu'à 14h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP68 (2 m / 30 min)',
    poids: '177 g',
  },
  'iPhone XS Max': {
    annee: 2018,
    ecran: '6,5" Super Retina OLED HDR',
    puce: 'Apple A12 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.8 + téléobjectif f/2.4, zoom 2x)',
    selfie: '7 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, stéréo',
    autonomie: "Jusqu'à 15h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP68 (2 m / 30 min)',
    poids: '208 g',
  },

  // ── 2019 ──────────────────────────────────────────────────────────────
  'iPhone 11': {
    annee: 2019,
    ecran: '6,1" Liquid Retina LCD',
    puce: 'Apple A13 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.8 + ultra grand-angle f/2.4)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, stéréo',
    autonomie: "Jusqu'à 17h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP68 (2 m / 30 min)',
    poids: '194 g',
  },
  'iPhone 11 Pro': {
    annee: 2019,
    ecran: '5,8" Super Retina XDR OLED',
    puce: 'Apple A13 Bionic',
    photo: 'Triple 12 Mpx (grand-angle + ultra grand-angle + téléobjectif 2x)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, Dolby Vision HDR',
    autonomie: "Jusqu'à 18h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP68 (4 m / 30 min)',
    poids: '188 g',
  },
  'iPhone 11 Pro Max': {
    annee: 2019,
    ecran: '6,5" Super Retina XDR OLED',
    puce: 'Apple A13 Bionic',
    photo: 'Triple 12 Mpx (grand-angle + ultra grand-angle + téléobjectif 2x)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, Dolby Vision HDR',
    autonomie: "Jusqu'à 20h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP68 (4 m / 30 min)',
    poids: '226 g',
  },

  // ── 2020 ──────────────────────────────────────────────────────────────
  'iPhone SE (2nd generation)': {
    annee: 2020,
    ecran: '4,7" Retina HD LCD',
    puce: 'Apple A13 Bionic',
    photo: '12 Mpx grand-angle f/1.8',
    selfie: '7 Mpx FaceTime HD (Touch ID)',
    video: '4K jusqu\'à 60 i/s',
    autonomie: "Jusqu'à 13h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '4G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '148 g',
  },
  'iPhone 12 mini': {
    annee: 2020,
    ecran: '5,4" Super Retina XDR OLED',
    puce: 'Apple A14 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.6 + ultra grand-angle f/2.4)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, Dolby Vision HDR',
    autonomie: "Jusqu'à 15h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '133 g',
  },
  'iPhone 12': {
    annee: 2020,
    ecran: '6,1" Super Retina XDR OLED',
    puce: 'Apple A14 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.6 + ultra grand-angle f/2.4)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, Dolby Vision HDR',
    autonomie: "Jusqu'à 17h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '164 g',
  },
  'iPhone 12 Pro': {
    annee: 2020,
    ecran: '6,1" Super Retina XDR OLED',
    puce: 'Apple A14 Bionic',
    photo: 'Triple 12 Mpx + LiDAR (grand-angle + ultra grand-angle + téléobjectif 2x)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, Dolby Vision HDR, ProRAW',
    autonomie: "Jusqu'à 17h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '187 g',
  },
  'iPhone 12 Pro Max': {
    annee: 2020,
    ecran: '6,7" Super Retina XDR OLED',
    puce: 'Apple A14 Bionic',
    photo: 'Triple 12 Mpx + LiDAR (grand-angle + ultra grand-angle + téléobjectif 2,5x)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K jusqu\'à 60 i/s, Dolby Vision HDR, ProRAW',
    autonomie: "Jusqu'à 20h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '226 g',
  },

  // ── 2021 ──────────────────────────────────────────────────────────────
  'iPhone 13 mini': {
    annee: 2021,
    ecran: '5,4" Super Retina XDR OLED',
    puce: 'Apple A15 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.6 + ultra grand-angle f/2.4)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K Dolby Vision, mode Cinématique',
    autonomie: "Jusqu'à 17h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '141 g',
  },
  'iPhone 13': {
    annee: 2021,
    ecran: '6,1" Super Retina XDR OLED',
    puce: 'Apple A15 Bionic',
    photo: 'Double 12 Mpx (grand-angle f/1.6 + ultra grand-angle f/2.4)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K Dolby Vision, mode Cinématique',
    autonomie: "Jusqu'à 19h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '174 g',
  },
  'iPhone 13 Pro': {
    annee: 2021,
    ecran: '6,1" Super Retina XDR ProMotion OLED (10–120 Hz)',
    puce: 'Apple A15 Bionic (5 cœurs GPU)',
    photo: 'Triple 12 Mpx + LiDAR (grand-angle + ultra grand-angle macro + téléobjectif 3x)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K Dolby Vision, mode Cinématique, ProRes',
    autonomie: "Jusqu'à 22h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '203 g',
  },
  'iPhone 13 Pro Max': {
    annee: 2021,
    ecran: '6,7" Super Retina XDR ProMotion OLED (10–120 Hz)',
    puce: 'Apple A15 Bionic (5 cœurs GPU)',
    photo: 'Triple 12 Mpx + LiDAR (grand-angle + ultra grand-angle macro + téléobjectif 3x)',
    selfie: '12 Mpx TrueDepth (Face ID)',
    video: '4K Dolby Vision, mode Cinématique, ProRes',
    autonomie: "Jusqu'à 28h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '238 g',
  },

  // ── 2022 ──────────────────────────────────────────────────────────────
  'iPhone SE (3rd generation)': {
    annee: 2022,
    ecran: '4,7" Retina HD LCD',
    puce: 'Apple A15 Bionic',
    photo: '12 Mpx grand-angle f/1.8',
    selfie: '7 Mpx FaceTime HD (Touch ID)',
    video: '4K jusqu\'à 60 i/s',
    autonomie: "Jusqu'à 15h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP67 (1 m / 30 min)',
    poids: '144 g',
  },
  'iPhone 14': {
    annee: 2022,
    ecran: '6,1" Super Retina XDR OLED',
    puce: 'Apple A15 Bionic (5 cœurs GPU)',
    photo: 'Double 12 Mpx (grand-angle f/1.5 + ultra grand-angle f/2.4)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, mode Cinématique, Action',
    autonomie: "Jusqu'à 20h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '172 g',
  },
  'iPhone 14 Plus': {
    annee: 2022,
    ecran: '6,7" Super Retina XDR OLED',
    puce: 'Apple A15 Bionic (5 cœurs GPU)',
    photo: 'Double 12 Mpx (grand-angle f/1.5 + ultra grand-angle f/2.4)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, mode Cinématique, Action',
    autonomie: "Jusqu'à 26h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '203 g',
  },
  'iPhone 14 Pro': {
    annee: 2022,
    ecran: '6,1" Super Retina XDR ProMotion (1–120 Hz, Always-On), Dynamic Island',
    puce: 'Apple A16 Bionic',
    photo: 'Triple 48 + 12 + 12 Mpx + LiDAR (téléobjectif 3x)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, mode Cinématique 4K, Action, ProRes',
    autonomie: "Jusqu'à 23h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '206 g',
  },
  'iPhone 14 Pro Max': {
    annee: 2022,
    ecran: '6,7" Super Retina XDR ProMotion (1–120 Hz, Always-On), Dynamic Island',
    puce: 'Apple A16 Bionic',
    photo: 'Triple 48 + 12 + 12 Mpx + LiDAR (téléobjectif 3x)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, mode Cinématique 4K, Action, ProRes',
    autonomie: "Jusqu'à 29h de lecture vidéo",
    connectique: 'Lightning',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '240 g',
  },

  // ── 2023 ──────────────────────────────────────────────────────────────
  'iPhone 15': {
    annee: 2023,
    ecran: '6,1" Super Retina XDR OLED, Dynamic Island',
    puce: 'Apple A16 Bionic',
    photo: 'Double 48 + 12 Mpx (téléobjectif 2x optique sur capteur principal)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, mode Cinématique 4K, Action',
    autonomie: "Jusqu'à 20h de lecture vidéo",
    connectique: 'USB-C',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '171 g',
  },
  'iPhone 15 Plus': {
    annee: 2023,
    ecran: '6,7" Super Retina XDR OLED, Dynamic Island',
    puce: 'Apple A16 Bionic',
    photo: 'Double 48 + 12 Mpx (téléobjectif 2x optique sur capteur principal)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, mode Cinématique 4K, Action',
    autonomie: "Jusqu'à 26h de lecture vidéo",
    connectique: 'USB-C',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '201 g',
  },
  'iPhone 15 Pro': {
    annee: 2023,
    ecran: '6,1" Super Retina XDR ProMotion (1–120 Hz, Always-On), Dynamic Island, châssis titane',
    puce: 'Apple A17 Pro',
    photo: 'Triple 48 + 12 + 12 Mpx + LiDAR (téléobjectif 3x)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, ProRes, Log, Académie Color',
    autonomie: "Jusqu'à 23h de lecture vidéo",
    connectique: 'USB-C (USB 3, 10 Gb/s)',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '187 g',
  },
  'iPhone 15 Pro Max': {
    annee: 2023,
    ecran: '6,7" Super Retina XDR ProMotion (1–120 Hz, Always-On), Dynamic Island, châssis titane',
    puce: 'Apple A17 Pro',
    photo: 'Triple 48 + 12 + 12 Mpx + LiDAR (téléobjectif tétraprisme 5x)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, ProRes, Log, Académie Color',
    autonomie: "Jusqu'à 29h de lecture vidéo",
    connectique: 'USB-C (USB 3, 10 Gb/s)',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '221 g',
  },

  // ── 2024 ──────────────────────────────────────────────────────────────
  'iPhone 16': {
    annee: 2024,
    ecran: '6,1" Super Retina XDR OLED, Dynamic Island',
    puce: 'Apple A18',
    photo: 'Double Fusion 48 + 12 Mpx (téléobjectif 2x sur capteur principal)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, micros audio spatial',
    autonomie: "Jusqu'à 22h de lecture vidéo",
    connectique: 'USB-C',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '170 g',
  },
  'iPhone 16 Plus': {
    annee: 2024,
    ecran: '6,7" Super Retina XDR OLED, Dynamic Island',
    puce: 'Apple A18',
    photo: 'Double Fusion 48 + 12 Mpx (téléobjectif 2x sur capteur principal)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision, micros audio spatial',
    autonomie: "Jusqu'à 27h de lecture vidéo",
    connectique: 'USB-C',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '199 g',
  },
  'iPhone 16 Pro': {
    annee: 2024,
    ecran: '6,3" Super Retina XDR ProMotion (1–120 Hz, Always-On), Dynamic Island, châssis titane',
    puce: 'Apple A18 Pro',
    photo: 'Triple Fusion 48 + 48 + 12 Mpx + LiDAR (téléobjectif tétraprisme 5x)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision 120 i/s, ProRes, Log, Académie Color',
    autonomie: "Jusqu'à 27h de lecture vidéo",
    connectique: 'USB-C (USB 3, 10 Gb/s)',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '199 g',
  },
  'iPhone 16 Pro Max': {
    annee: 2024,
    ecran: '6,9" Super Retina XDR ProMotion (1–120 Hz, Always-On), Dynamic Island, châssis titane',
    puce: 'Apple A18 Pro',
    photo: 'Triple Fusion 48 + 48 + 12 Mpx + LiDAR (téléobjectif tétraprisme 5x)',
    selfie: '12 Mpx TrueDepth autofocus (Face ID)',
    video: '4K Dolby Vision 120 i/s, ProRes, Log, Académie Color',
    autonomie: "Jusqu'à 33h de lecture vidéo",
    connectique: 'USB-C (USB 3, 10 Gb/s)',
    reseau: '5G',
    resistance: 'IP68 (6 m / 30 min)',
    poids: '227 g',
  },
};

// Lookup avec normalisation (espaces multiples, casse).
export function getIphoneSpecs(model: string | null | undefined): IphoneSpec | null {
  if (!model) return null;
  const direct = SPECS[model];
  if (direct) return direct;
  const normalized = model.trim().replace(/\s+/g, ' ');
  return SPECS[normalized] ?? null;
}

// Ordre stable des lignes pour le rendu du tableau.
export const SPEC_ROWS: { key: keyof IphoneSpec; label: string }[] = [
  { key: 'ecran',       label: 'Écran' },
  { key: 'puce',        label: 'Puce' },
  { key: 'photo',       label: 'Appareil photo' },
  { key: 'selfie',      label: 'Caméra avant' },
  { key: 'video',       label: 'Vidéo' },
  { key: 'autonomie',   label: 'Autonomie' },
  { key: 'reseau',      label: 'Réseau' },
  { key: 'connectique', label: 'Connectique' },
  { key: 'resistance',  label: 'Résistance eau / poussière' },
  { key: 'poids',       label: 'Poids' },
  { key: 'annee',       label: 'Année de sortie' },
];
