// ─────────────────────────────────────────────────────────────────────────
// Official curated product images (brand + model [+ color] → image URL).
//
// WHY: Foxway/Fluxitron only ships one generic photo per product (shared by
// every color), and ~15% of the catalog has no photo at all. This map lets us
// override with our own clean photos as they become available.
//
// HOW TO ADD AN ENTRY:
//   1. Build the key with modelImageKey(brand, model[, color]):
//        - brand + model            → applies to every color of that model
//        - brand + model + color    → applies to one specific color (wins)
//      Keys are lowercased & trimmed automatically by modelImageKey().
//   2. `color` must match the product's STORED color value (English, e.g.
//      "Black", "Green") — that is what resolveProductImage() passes in.
//   3. The value is the image URL: a local path under /public (recommended,
//      e.g. "/products/official/iphone-14-pro.jpg") or an absolute URL.
//
// resolveProductImage() (see productImage.ts) reads this map BEFORE the
// Foxway images and the neutral placeholder.
//
// Rempli le 12/06/2026 : 127 couples modèle×couleur couverts par des
// packshots OFFICIELS Apple (store.storeimages.cdn-apple.com — PNG fond
// transparent, cf. public/image-sources.json). Les couples restants sont
// listés dans scripts/photos-missing-report.json (placeholder en attendant).
//
// IMPORTANT : ne JAMAIS ajouter d'entrée « modèle seul » (sans couleur) — elle
// écraserait l'image couleur correcte du SKU et afficherait une teinte fausse.
// ─────────────────────────────────────────────────────────────────────────

export const MODEL_IMAGES: Record<string, string> = {
  "apple|iphone 11 pro max|gold": "/images/apple-iphone-11-pro-max-gold.png",
  "apple|iphone 11 pro max|midnight green": "/images/apple-iphone-11-pro-max-midnight-green.png",
  "apple|iphone 11 pro max|silver": "/images/apple-iphone-11-pro-max-silver.png",
  "apple|iphone 11 pro|gold": "/images/apple-iphone-11-pro-gold.png",
  "apple|iphone 11 pro|midnight green": "/images/apple-iphone-11-pro-midnight-green.png",
  "apple|iphone 11 pro|silver": "/images/apple-iphone-11-pro-silver.png",
  "apple|iphone 11|black": "/images/apple-iphone-11-black.png",
  "apple|iphone 11|green": "/images/apple-iphone-11-green.png",
  "apple|iphone 11|product red": "/images/apple-iphone-11-product-red.png",
  "apple|iphone 11|purple": "/images/apple-iphone-11-purple.png",
  "apple|iphone 11|white": "/images/apple-iphone-11-white.png",
  "apple|iphone 11|yellow": "/images/apple-iphone-11-yellow.png",
  "apple|iphone 12 mini|black": "/images/apple-iphone-12-mini-black.png",
  "apple|iphone 12 mini|blue": "/images/apple-iphone-12-mini-blue.png",
  "apple|iphone 12 mini|green": "/images/apple-iphone-12-mini-green.png",
  "apple|iphone 12 mini|product red": "/images/apple-iphone-12-mini-product-red.png",
  "apple|iphone 12 mini|purple": "/images/apple-iphone-12-mini-purple.png",
  "apple|iphone 12 mini|white": "/images/apple-iphone-12-mini-white.png",
  "apple|iphone 12|black": "/images/apple-iphone-12-black.png",
  "apple|iphone 12|blue": "/images/apple-iphone-12-blue.png",
  "apple|iphone 12|green": "/images/apple-iphone-12-green.png",
  "apple|iphone 12|product red": "/images/apple-iphone-12-product-red.png",
  "apple|iphone 12|purple": "/images/apple-iphone-12-purple.png",
  "apple|iphone 12|white": "/images/apple-iphone-12-white.png",
  "apple|iphone 13 mini|blue": "/images/apple-iphone-13-mini-blue.png",
  "apple|iphone 13 mini|green": "/images/apple-iphone-13-mini-green.png",
  "apple|iphone 13 mini|midnight": "/images/apple-iphone-13-mini-midnight.png",
  "apple|iphone 13 mini|pink": "/images/apple-iphone-13-mini-pink.png",
  "apple|iphone 13 mini|product red": "/images/apple-iphone-13-mini-product-red.png",
  "apple|iphone 13 mini|starlight": "/images/apple-iphone-13-mini-starlight.png",
  "apple|iphone 13 pro max|alpine green": "/images/apple-iphone-13-pro-max-alpine-green.png",
  "apple|iphone 13 pro max|gold": "/images/apple-iphone-13-pro-max-gold.png",
  "apple|iphone 13 pro max|graphite": "/images/apple-iphone-13-pro-max-graphite.png",
  "apple|iphone 13 pro max|sierra blue": "/images/apple-iphone-13-pro-max-sierra-blue.png",
  "apple|iphone 13 pro max|silver": "/images/apple-iphone-13-pro-max-silver.png",
  "apple|iphone 13 pro|alpine green": "/images/apple-iphone-13-pro-alpine-green.png",
  "apple|iphone 13 pro|gold": "/images/apple-iphone-13-pro-gold.png",
  "apple|iphone 13 pro|graphite": "/images/apple-iphone-13-pro-graphite.png",
  "apple|iphone 13 pro|sierra blue": "/images/apple-iphone-13-pro-sierra-blue.png",
  "apple|iphone 13 pro|silver": "/images/apple-iphone-13-pro-silver.png",
  "apple|iphone 13|blue": "/images/apple-iphone-13-blue.png",
  "apple|iphone 13|green": "/images/apple-iphone-13-green.png",
  "apple|iphone 13|midnight": "/images/apple-iphone-13-midnight.png",
  "apple|iphone 13|pink": "/images/apple-iphone-13-pink.png",
  "apple|iphone 13|product red": "/images/apple-iphone-13-product-red.png",
  "apple|iphone 13|starlight": "/images/apple-iphone-13-starlight.png",
  "apple|iphone 14 plus|blue": "/images/apple-iphone-14-plus-blue.png",
  "apple|iphone 14 plus|midnight": "/images/apple-iphone-14-plus-midnight.png",
  "apple|iphone 14 plus|product red": "/images/apple-iphone-14-plus-product-red.png",
  "apple|iphone 14 plus|purple": "/images/apple-iphone-14-plus-purple.png",
  "apple|iphone 14 plus|starlight": "/images/apple-iphone-14-plus-starlight.png",
  "apple|iphone 14 plus|yellow": "/images/apple-iphone-14-plus-yellow.png",
  "apple|iphone 14 pro max|deep purple": "/images/apple-iphone-14-pro-max-deep-purple.png",
  "apple|iphone 14 pro max|gold": "/images/apple-iphone-14-pro-max-gold.png",
  "apple|iphone 14 pro max|silver": "/images/apple-iphone-14-pro-max-silver.png",
  "apple|iphone 14 pro max|space black": "/images/apple-iphone-14-pro-max-space-black.png",
  "apple|iphone 14 pro|deep purple": "/images/apple-iphone-14-pro-deep-purple.png",
  "apple|iphone 14 pro|gold": "/images/apple-iphone-14-pro-gold.png",
  "apple|iphone 14 pro|silver": "/images/apple-iphone-14-pro-silver.png",
  "apple|iphone 14 pro|space black": "/images/apple-iphone-14-pro-space-black.png",
  "apple|iphone 14|blue": "/images/apple-iphone-14-blue.png",
  "apple|iphone 14|midnight": "/images/apple-iphone-14-midnight.png",
  "apple|iphone 14|product red": "/images/apple-iphone-14-product-red.png",
  "apple|iphone 14|purple": "/images/apple-iphone-14-purple.png",
  "apple|iphone 14|starlight": "/images/apple-iphone-14-starlight.png",
  "apple|iphone 14|yellow": "/images/apple-iphone-14-yellow.png",
  "apple|iphone 15 plus|black": "/images/apple-iphone-15-plus-black.png",
  "apple|iphone 15 plus|blue": "/images/apple-iphone-15-plus-blue.png",
  "apple|iphone 15 plus|green": "/images/apple-iphone-15-plus-green.png",
  "apple|iphone 15 plus|pink": "/images/apple-iphone-15-plus-pink.png",
  "apple|iphone 15 plus|yellow": "/images/apple-iphone-15-plus-yellow.png",
  "apple|iphone 15 pro max|black titanium": "/images/apple-iphone-15-pro-max-black-titanium.png",
  "apple|iphone 15 pro max|blue titanium": "/images/apple-iphone-15-pro-max-blue-titanium.png",
  "apple|iphone 15 pro max|natural titanium": "/images/apple-iphone-15-pro-max-natural-titanium.png",
  "apple|iphone 15 pro max|white titanium": "/images/apple-iphone-15-pro-max-white-titanium.png",
  "apple|iphone 15 pro|black titanium": "/images/apple-iphone-15-pro-black-titanium.png",
  "apple|iphone 15 pro|blue titanium": "/images/apple-iphone-15-pro-blue-titanium.png",
  "apple|iphone 15 pro|natural titanium": "/images/apple-iphone-15-pro-natural-titanium.png",
  "apple|iphone 15 pro|white titanium": "/images/apple-iphone-15-pro-white-titanium.png",
  "apple|iphone 15|black": "/images/apple-iphone-15-black.png",
  "apple|iphone 15|blue": "/images/apple-iphone-15-blue.png",
  "apple|iphone 15|green": "/images/apple-iphone-15-green.png",
  "apple|iphone 15|pink": "/images/apple-iphone-15-pink.png",
  "apple|iphone 15|yellow": "/images/apple-iphone-15-yellow.png",
  "apple|iphone 16 plus|black": "/images/apple-iphone-16-plus-black.png",
  "apple|iphone 16 plus|pink": "/images/apple-iphone-16-plus-pink.png",
  "apple|iphone 16 plus|teal": "/images/apple-iphone-16-plus-teal.png",
  "apple|iphone 16 plus|ultramarine": "/images/apple-iphone-16-plus-ultramarine.png",
  "apple|iphone 16 plus|white": "/images/apple-iphone-16-plus-white.png",
  "apple|iphone 16 pro max|black titanium": "/images/apple-iphone-16-pro-max-black-titanium.png",
  "apple|iphone 16 pro max|desert titanium": "/images/apple-iphone-16-pro-max-desert-titanium.png",
  "apple|iphone 16 pro max|natural titanium": "/images/apple-iphone-16-pro-max-natural-titanium.png",
  "apple|iphone 16 pro max|white titanium": "/images/apple-iphone-16-pro-max-white-titanium.png",
  "apple|iphone 16 pro|black titanium": "/images/apple-iphone-16-pro-black-titanium.png",
  "apple|iphone 16 pro|desert titanium": "/images/apple-iphone-16-pro-desert-titanium.png",
  "apple|iphone 16 pro|natural titanium": "/images/apple-iphone-16-pro-natural-titanium.png",
  "apple|iphone 16 pro|white titanium": "/images/apple-iphone-16-pro-white-titanium.png",
  "apple|iphone 16|black": "/images/apple-iphone-16-black.png",
  "apple|iphone 16|pink": "/images/apple-iphone-16-pink.png",
  "apple|iphone 16|teal": "/images/apple-iphone-16-teal.png",
  "apple|iphone 16|ultramarine": "/images/apple-iphone-16-ultramarine.png",
  "apple|iphone 16|white": "/images/apple-iphone-16-white.png",
  "apple|iphone 7|black": "/images/apple-iphone-7-black.png",
  "apple|iphone 7|gold": "/images/apple-iphone-7-gold.png",
  "apple|iphone 7|jet black": "/images/apple-iphone-7-jet-black.png",
  "apple|iphone 7|rose gold": "/images/apple-iphone-7-rose-gold.png",
  "apple|iphone 7|silver": "/images/apple-iphone-7-silver.png",
  "apple|iphone 8|gold": "/images/apple-iphone-8-gold.png",
  "apple|iphone 8|product red": "/images/apple-iphone-8-product-red.png",
  "apple|iphone 8|silver": "/images/apple-iphone-8-silver.png",
  "apple|iphone se (2nd generation)|black": "/images/apple-iphone-se-2nd-generation-black.png",
  "apple|iphone se (2nd generation)|product red": "/images/apple-iphone-se-2nd-generation-product-red.png",
  "apple|iphone se (2nd generation)|white": "/images/apple-iphone-se-2nd-generation-white.png",
  "apple|iphone se (3rd generation)|midnight": "/images/apple-iphone-se-3rd-generation-midnight.png",
  "apple|iphone se (3rd generation)|product red": "/images/apple-iphone-se-3rd-generation-product-red.png",
  "apple|iphone se (3rd generation)|starlight": "/images/apple-iphone-se-3rd-generation-starlight.png",
  "apple|iphone x|silver": "/images/apple-iphone-x-silver.png",
  "apple|iphone xr|black": "/images/apple-iphone-xr-black.png",
  "apple|iphone xr|blue": "/images/apple-iphone-xr-blue.png",
  "apple|iphone xr|coral": "/images/apple-iphone-xr-coral.png",
  "apple|iphone xr|product red": "/images/apple-iphone-xr-product-red.png",
  "apple|iphone xr|white": "/images/apple-iphone-xr-white.png",
  "apple|iphone xr|yellow": "/images/apple-iphone-xr-yellow.png",
  "apple|iphone xs max|gold": "/images/apple-iphone-xs-max-gold.png",
  "apple|iphone xs max|silver": "/images/apple-iphone-xs-max-silver.png",
  "apple|iphone xs|gold": "/images/apple-iphone-xs-gold.png",
  "apple|iphone xs|silver": "/images/apple-iphone-xs-silver.png",
  // === AUTO-GENERATED phone-images START (ne pas editer a la main) ===
  "apple|iphone 12 pro max|blue": "/images/apple-iphone-12-pro-max-blue.png",
  "apple|iphone 12 pro max|gold": "/images/apple-iphone-12-pro-max-gold.png",
  "apple|iphone 12 pro max|graphite": "/images/apple-iphone-12-pro-max-graphite.png",
  "apple|iphone 12 pro max|silver": "/images/apple-iphone-12-pro-max-silver.png",
  "apple|iphone 12 pro|blue": "/images/apple-iphone-12-pro-blue.png",
  "apple|iphone 12 pro|gold": "/images/apple-iphone-12-pro-gold.png",
  "apple|iphone 12 pro|graphite": "/images/apple-iphone-12-pro-graphite.png",
  "apple|iphone 17 pro max|blue": "/images/apple-iphone-17-pro-max-blue.png",
  "apple|iphone 17 pro max|orange": "/images/apple-iphone-17-pro-max-orange.png",
  "apple|iphone 17 pro|blue": "/images/apple-iphone-17-pro-blue.png",
  "apple|iphone 17e|black": "/images/apple-iphone-17e-black.png",
  "apple|iphone 17e|white": "/images/apple-iphone-17e-white.png",
  "apple|iphone 17|black": "/images/apple-iphone-17-black.png",
  "apple|iphone 17|purple": "/images/apple-iphone-17-purple.png",
  "apple|iphone 17|white": "/images/apple-iphone-17-white.png",
  "apple|iphone air|black": "/images/apple-iphone-air-black.png",
  "apple|iphone air|blue": "/images/apple-iphone-air-blue.png",
  "apple|iphone air|gold": "/images/apple-iphone-air-gold.png",
  "apple|iphone air|white": "/images/apple-iphone-air-white.png",
  "apple|iphone se (2022)|red": "/images/apple-iphone-se-2022-red.png",
  "apple|iphone se (2022)|white": "/images/apple-iphone-se-2022-white.png",
  "google|pixel 10 5g|black": "/images/google-pixel-10-5g-black.png",
  "google|pixel 10 5g|blue": "/images/google-pixel-10-5g-blue.png",
  "google|pixel 10 pro 5g|black": "/images/google-pixel-10-pro-5g-black.png",
  "google|pixel 10 pro 5g|blue": "/images/google-pixel-10-pro-5g-blue.png",
  "google|pixel 10 pro 5g|white": "/images/google-pixel-10-pro-5g-white.png",
  "google|pixel 10 pro xl 5g|blue": "/images/google-pixel-10-pro-xl-5g-blue.png",
  "google|pixel 10a 5g|black": "/images/google-pixel-10a-5g-black.png",
  "google|pixel 7 5g|black": "/images/google-pixel-7-5g-black.png",
  "google|pixel 7 pro 5g|white": "/images/google-pixel-7-pro-5g-white.png",
  "google|pixel 7a 5g|blue": "/images/google-pixel-7a-5g-blue.png",
  "google|pixel 7a 5g|white": "/images/google-pixel-7a-5g-white.png",
  "google|pixel 8 5g|pink": "/images/google-pixel-8-5g-pink.png",
  "google|pixel 8 pro 5g|black": "/images/google-pixel-8-pro-5g-black.png",
  "google|pixel 8 pro 5g|blue": "/images/google-pixel-8-pro-5g-blue.png",
  "google|pixel 8 pro 5g|white": "/images/google-pixel-8-pro-5g-white.png",
  "google|pixel 8a 5g|beige": "/images/google-pixel-8a-5g-beige.png",
  "google|pixel 8a 5g|blue": "/images/google-pixel-8a-5g-blue.png",
  "google|pixel 9 pro 5g|pink": "/images/google-pixel-9-pro-5g-pink.png",
  "google|pixel 9 pro xl 5g|grey": "/images/google-pixel-9-pro-xl-5g-grey.png",
  "google|pixel 9a 5g|purple": "/images/google-pixel-9a-5g-purple.png",
  "oneplus|13 5g|black": "/images/oneplus-13-5g-black.png",
  "oneplus|13 5g|blue": "/images/oneplus-13-5g-blue.png",
  "oneplus|13r 5g|silver": "/images/oneplus-13r-5g-silver.png",
  "oneplus|nord 5 5g|grey": "/images/oneplus-nord-5-5g-grey.png",
  "oneplus|nord 5 5g|ice blue": "/images/oneplus-nord-5-5g-ice-blue.png",
  "oneplus|nord ce 5 5g|black": "/images/oneplus-nord-ce-5-5g-black.png",
  "oneplus|nord ce 5 5g|white": "/images/oneplus-nord-ce-5-5g-white.png",
  "samsung|galaxy a54 5g|black": "/images/samsung-galaxy-a54-5g-black.png",
  "samsung|galaxy a54 5g|green": "/images/samsung-galaxy-a54-5g-green.png",
  "samsung|galaxy a54 5g|white": "/images/samsung-galaxy-a54-5g-white.png",
  "samsung|galaxy a54|blanc": "/images/samsung-galaxy-a54-white.png",
  "samsung|galaxy a55 5g|ice blue": "/images/samsung-galaxy-a55-5g-ice-blue.png",
  "samsung|galaxy a55 5g|purple": "/images/samsung-galaxy-a55-5g-purple.png",
  "samsung|galaxy a55 5g|yellow": "/images/samsung-galaxy-a55-5g-yellow.png",
  "samsung|galaxy a56 5g|black": "/images/samsung-galaxy-a56-5g-black.png",
  "samsung|galaxy a56 5g|green": "/images/samsung-galaxy-a56-5g-green.png",
  "samsung|galaxy a56 5g|pink": "/images/samsung-galaxy-a56-5g-pink.png",
  "samsung|galaxy a73 5g|grey": "/images/samsung-galaxy-a73-5g-grey.png",
  "samsung|galaxy s21 fe 5g|black": "/images/samsung-galaxy-s21-fe-5g-black.png",
  "samsung|galaxy s21 fe 5g|graphite": "/images/samsung-galaxy-s21-fe-5g-graphite.png",
  "samsung|galaxy s21 fe 5g|green": "/images/samsung-galaxy-s21-fe-5g-green.png",
  "samsung|galaxy s21 fe 5g|purple": "/images/samsung-galaxy-s21-fe-5g-purple.png",
  "samsung|galaxy s21 fe 5g|white": "/images/samsung-galaxy-s21-fe-5g-white.png",
  "samsung|galaxy s21 plus|black": "/images/samsung-galaxy-s21-plus-black.png",
  "samsung|galaxy s21 plus|gold": "/images/samsung-galaxy-s21-plus-gold.png",
  "samsung|galaxy s21 plus|purple": "/images/samsung-galaxy-s21-plus-purple.png",
  "samsung|galaxy s21 plus|red": "/images/samsung-galaxy-s21-plus-red.png",
  "samsung|galaxy s21 plus|silver": "/images/samsung-galaxy-s21-plus-silver.png",
  "samsung|galaxy s21 ultra 5g|black": "/images/samsung-galaxy-s21-ultra-5g-black.png",
  "samsung|galaxy s21 ultra 5g|grey": "/images/samsung-galaxy-s21-ultra-5g-grey.png",
  "samsung|galaxy s21 ultra 5g|silver": "/images/samsung-galaxy-s21-ultra-5g-silver.png",
  "samsung|galaxy s22 5g|grey": "/images/samsung-galaxy-s22-5g-grey.png",
  "samsung|galaxy s22 5g|pink": "/images/samsung-galaxy-s22-5g-pink.png",
  "samsung|galaxy s22 5g|purple": "/images/samsung-galaxy-s22-5g-purple.png",
  "samsung|galaxy s22 5g|white": "/images/samsung-galaxy-s22-5g-white.png",
  "samsung|galaxy s22 plus 5g|black": "/images/samsung-galaxy-s22-plus-5g-black.png",
  "samsung|galaxy s22 plus 5g|blue": "/images/samsung-galaxy-s22-plus-5g-blue.png",
  "samsung|galaxy s22 plus 5g|grey": "/images/samsung-galaxy-s22-plus-5g-grey.png",
  "samsung|galaxy s22 plus 5g|pink": "/images/samsung-galaxy-s22-plus-5g-pink.png",
  "samsung|galaxy s22 plus 5g|white": "/images/samsung-galaxy-s22-plus-5g-white.png",
  "samsung|galaxy s22 ultra 5g|black": "/images/samsung-galaxy-s22-ultra-5g-black.png",
  "samsung|galaxy s22 ultra 5g|graphite": "/images/samsung-galaxy-s22-ultra-5g-graphite.png",
  "samsung|galaxy s22 ultra 5g|white": "/images/samsung-galaxy-s22-ultra-5g-white.png",
  "samsung|galaxy s23 5g|lime": "/images/samsung-galaxy-s23-5g-lime.png",
  "samsung|galaxy s23 fe 5g|beige": "/images/samsung-galaxy-s23-fe-5g-beige.png",
  "samsung|galaxy s23 fe 5g|graphite": "/images/samsung-galaxy-s23-fe-5g-graphite.png",
  "samsung|galaxy s23 fe 5g|green": "/images/samsung-galaxy-s23-fe-5g-green.png",
  "samsung|galaxy s23 fe 5g|purple": "/images/samsung-galaxy-s23-fe-5g-purple.png",
  "samsung|galaxy s23 plus 5g|beige": "/images/samsung-galaxy-s23-plus-5g-beige.png",
  "samsung|galaxy s23 ultra 5g|beige": "/images/samsung-galaxy-s23-ultra-5g-beige.png",
  "samsung|galaxy s23 ultra 5g|blue": "/images/samsung-galaxy-s23-ultra-5g-blue.png",
  "samsung|galaxy s23 ultra 5g|green": "/images/samsung-galaxy-s23-ultra-5g-green.png",
  "samsung|galaxy s23 ultra 5g|lime": "/images/samsung-galaxy-s23-ultra-5g-lime.png",
  "samsung|galaxy s23 ultra 5g|purple": "/images/samsung-galaxy-s23-ultra-5g-purple.png",
  "samsung|galaxy s23 ultra 5g|red": "/images/samsung-galaxy-s23-ultra-5g-red.png",
  "samsung|galaxy s24 5g|yellow": "/images/samsung-galaxy-s24-5g-yellow.png",
  "samsung|galaxy s24 fe 5g|mint": "/images/samsung-galaxy-s24-fe-5g-mint.png",
  "samsung|galaxy s24 plus 5g|black": "/images/samsung-galaxy-s24-plus-5g-black.png",
  "samsung|galaxy s24 plus 5g|blue": "/images/samsung-galaxy-s24-plus-5g-blue.png",
  "samsung|galaxy s24 plus 5g|green": "/images/samsung-galaxy-s24-plus-5g-green.png",
  "samsung|galaxy s24 plus 5g|yellow": "/images/samsung-galaxy-s24-plus-5g-yellow.png",
  "samsung|galaxy s24 ultra 5g|black": "/images/samsung-galaxy-s24-ultra-5g-black.png",
  "samsung|galaxy s24 ultra 5g|blue": "/images/samsung-galaxy-s24-ultra-5g-blue.png",
  "samsung|galaxy s24 ultra 5g|purple": "/images/samsung-galaxy-s24-ultra-5g-purple.png",
  "samsung|galaxy s24 ultra 5g|yellow": "/images/samsung-galaxy-s24-ultra-5g-yellow.png",
  "samsung|galaxy s24 ultra|noir": "/images/samsung-galaxy-s24-ultra-black.png",
  "samsung|galaxy s25 5g|ice blue": "/images/samsung-galaxy-s25-5g-ice-blue.png",
  "samsung|galaxy s25 5g|mint": "/images/samsung-galaxy-s25-5g-mint.png",
  "samsung|galaxy s25 5g|pink": "/images/samsung-galaxy-s25-5g-pink.png",
  "samsung|galaxy s25 5g|silver": "/images/samsung-galaxy-s25-5g-silver.png",
  "samsung|galaxy s25 edge 5g|ice blue": "/images/samsung-galaxy-s25-edge-5g-ice-blue.png",
  "samsung|galaxy s25 edge 5g|jet black": "/images/samsung-galaxy-s25-edge-5g-jet-black.png",
  "samsung|galaxy s25 edge 5g|silver": "/images/samsung-galaxy-s25-edge-5g-silver.png",
  "samsung|galaxy s25 fe 5g|black": "/images/samsung-galaxy-s25-fe-5g-black.png",
  "samsung|galaxy s25 fe 5g|blue": "/images/samsung-galaxy-s25-fe-5g-blue.png",
  "samsung|galaxy s25 fe 5g|ice blue": "/images/samsung-galaxy-s25-fe-5g-ice-blue.png",
  "samsung|galaxy s25 plus 5g|mint": "/images/samsung-galaxy-s25-plus-5g-mint.png",
  "samsung|galaxy s25 plus 5g|pink": "/images/samsung-galaxy-s25-plus-5g-pink.png",
  "samsung|galaxy s25 ultra 5g|blue": "/images/samsung-galaxy-s25-ultra-5g-blue.png",
  "samsung|galaxy s25 ultra 5g|green": "/images/samsung-galaxy-s25-ultra-5g-green.png",
  "samsung|galaxy s25 ultra 5g|grey": "/images/samsung-galaxy-s25-ultra-5g-grey.png",
  "samsung|galaxy s25 ultra 5g|jet black": "/images/samsung-galaxy-s25-ultra-5g-jet-black.png",
  "samsung|galaxy s25 ultra 5g|pink": "/images/samsung-galaxy-s25-ultra-5g-pink.png",
  "samsung|galaxy s25 ultra 5g|silver": "/images/samsung-galaxy-s25-ultra-5g-silver.png",
  "samsung|galaxy s26 5g|black": "/images/samsung-galaxy-s26-5g-black.png",
  "samsung|galaxy s26 5g|purple": "/images/samsung-galaxy-s26-5g-purple.png",
  "samsung|galaxy s26 5g|silver": "/images/samsung-galaxy-s26-5g-silver.png",
  "samsung|galaxy s26 5g|white": "/images/samsung-galaxy-s26-5g-white.png",
  "samsung|galaxy s26 plus 5g|purple": "/images/samsung-galaxy-s26-plus-5g-purple.png",
  "samsung|galaxy s26 plus 5g|silver": "/images/samsung-galaxy-s26-plus-5g-silver.png",
  "samsung|galaxy s26 plus 5g|white": "/images/samsung-galaxy-s26-plus-5g-white.png",
  "samsung|galaxy s26 ultra 5g|black": "/images/samsung-galaxy-s26-ultra-5g-black.png",
  "samsung|galaxy s26 ultra 5g|blue": "/images/samsung-galaxy-s26-ultra-5g-blue.png",
  "samsung|galaxy s26 ultra 5g|pink": "/images/samsung-galaxy-s26-ultra-5g-pink.png",
  "samsung|galaxy s26 ultra 5g|purple": "/images/samsung-galaxy-s26-ultra-5g-purple.png",
  "samsung|galaxy s26 ultra 5g|silver": "/images/samsung-galaxy-s26-ultra-5g-silver.png",
  "samsung|galaxy s26 ultra 5g|white": "/images/samsung-galaxy-s26-ultra-5g-white.png",
  "samsung|galaxy z flip3 5g|black": "/images/samsung-galaxy-z-flip3-5g-black.png",
  "samsung|galaxy z flip3 5g|green": "/images/samsung-galaxy-z-flip3-5g-green.png",
  "samsung|galaxy z flip4 5g|graphite": "/images/samsung-galaxy-z-flip4-5g-graphite.png",
  "samsung|galaxy z flip4 5g|grey": "/images/samsung-galaxy-z-flip4-5g-grey.png",
  "samsung|galaxy z flip4 5g|purple": "/images/samsung-galaxy-z-flip4-5g-purple.png",
  "samsung|galaxy z flip4 5g|rose gold": "/images/samsung-galaxy-z-flip4-5g-rose-gold.png",
  "samsung|galaxy z flip5 5g|graphite": "/images/samsung-galaxy-z-flip5-5g-graphite.png",
  "samsung|galaxy z flip5 5g|grey": "/images/samsung-galaxy-z-flip5-5g-grey.png",
  "samsung|galaxy z flip5 5g|mint": "/images/samsung-galaxy-z-flip5-5g-mint.png",
  "samsung|galaxy z flip5 5g|purple": "/images/samsung-galaxy-z-flip5-5g-purple.png",
  "samsung|galaxy z flip6 5g|blue": "/images/samsung-galaxy-z-flip6-5g-blue.png",
  "samsung|galaxy z flip6 5g|green": "/images/samsung-galaxy-z-flip6-5g-green.png",
  "samsung|galaxy z flip6 5g|silver": "/images/samsung-galaxy-z-flip6-5g-silver.png",
  "samsung|galaxy z flip6 5g|yellow": "/images/samsung-galaxy-z-flip6-5g-yellow.png",
  "samsung|galaxy z flip7 5g|blue": "/images/samsung-galaxy-z-flip7-5g-blue.png",
  "samsung|galaxy z flip7 5g|jet black": "/images/samsung-galaxy-z-flip7-5g-jet-black.png",
  "samsung|galaxy z flip7 5g|mint": "/images/samsung-galaxy-z-flip7-5g-mint.png",
  "samsung|galaxy z flip7 5g|red": "/images/samsung-galaxy-z-flip7-5g-red.png",
  "samsung|galaxy z flip7 fe 5g|black": "/images/samsung-galaxy-z-flip7-fe-5g-black.png",
  "samsung|galaxy z flip7 fe 5g|white": "/images/samsung-galaxy-z-flip7-fe-5g-white.png",
  "samsung|galaxy z fold3 5g|black": "/images/samsung-galaxy-z-fold3-5g-black.png",
  "samsung|galaxy z fold3 5g|green": "/images/samsung-galaxy-z-fold3-5g-green.png",
  "samsung|galaxy z fold3 5g|silver": "/images/samsung-galaxy-z-fold3-5g-silver.png",
  "samsung|galaxy z fold4 5g|beige": "/images/samsung-galaxy-z-fold4-5g-beige.png",
  "samsung|galaxy z fold4 5g|black": "/images/samsung-galaxy-z-fold4-5g-black.png",
  "samsung|galaxy z fold4 5g|grey": "/images/samsung-galaxy-z-fold4-5g-grey.png",
  "samsung|galaxy z fold6 5g|black": "/images/samsung-galaxy-z-fold6-5g-black.png",
  "samsung|galaxy z fold6 5g|blue": "/images/samsung-galaxy-z-fold6-5g-blue.png",
  "samsung|galaxy z fold6 5g|silver": "/images/samsung-galaxy-z-fold6-5g-silver.png",
  "samsung|galaxy z fold7 5g|blue": "/images/samsung-galaxy-z-fold7-5g-blue.png",
  "samsung|galaxy z fold7 5g|green": "/images/samsung-galaxy-z-fold7-5g-green.png",
  "samsung|s24|noir": "/images/samsung-galaxy-s24-black.png",
  "xiaomi|13 5g|green": "/images/xiaomi-13-5g-green.png",
  "xiaomi|13 lite 5g|black": "/images/xiaomi-13-lite-5g-black.png",
  "xiaomi|13 lite 5g|blue": "/images/xiaomi-13-lite-5g-blue.png",
  "xiaomi|13 ultra 5g|black": "/images/xiaomi-13-ultra-5g-black.png",
  "xiaomi|13t 5g|black": "/images/xiaomi-13t-5g-black.png",
  "xiaomi|13t pro 5g|black": "/images/xiaomi-13t-pro-5g-black.png",
  "xiaomi|13t pro 5g|blue": "/images/xiaomi-13t-pro-5g-blue.png",
  "xiaomi|14 pro 5g|black": "/images/xiaomi-14-pro-5g-black.png",
  "xiaomi|14 ultra 5g|white": "/images/xiaomi-14-ultra-5g-white.png",
  "xiaomi|14t 5g|blue": "/images/xiaomi-14t-5g-blue.png",
  "xiaomi|14t 5g|grey": "/images/xiaomi-14t-5g-grey.png",
  "xiaomi|14t pro 5g|black": "/images/xiaomi-14t-pro-5g-black.png",
  "xiaomi|14t pro 5g|grey": "/images/xiaomi-14t-pro-5g-grey.png",
  "xiaomi|15 5g|black": "/images/xiaomi-15-5g-black.png",
  "xiaomi|15 5g|green": "/images/xiaomi-15-5g-green.png",
  "xiaomi|15 5g|silver": "/images/xiaomi-15-5g-silver.png",
  "xiaomi|15 5g|white": "/images/xiaomi-15-5g-white.png",
  "xiaomi|15 ultra 5g|black": "/images/xiaomi-15-ultra-5g-black.png",
  "xiaomi|15 ultra 5g|silver": "/images/xiaomi-15-ultra-5g-silver.png",
  "xiaomi|15t 5g|black": "/images/xiaomi-15t-5g-black.png",
  "xiaomi|15t pro 5g|black": "/images/xiaomi-15t-pro-5g-black.png",
  "xiaomi|17 ultra 5g|white": "/images/xiaomi-17-ultra-5g-white.png",
  "xiaomi|poco c65|black": "/images/xiaomi-poco-c65-black.png",
  "xiaomi|poco m4 pro 5g|blue": "/images/xiaomi-poco-m4-pro-5g-blue.png",
  "xiaomi|poco m4 pro 5g|yellow": "/images/xiaomi-poco-m4-pro-5g-yellow.png",
  "xiaomi|poco x5 pro 5g|yellow": "/images/xiaomi-poco-x5-pro-5g-yellow.png",
  "xiaomi|redmi 12 5g|black": "/images/xiaomi-redmi-12-5g-black.png",
  "xiaomi|redmi 14c|blue": "/images/xiaomi-redmi-14c-blue.png",
  "xiaomi|redmi 15c 4g|black": "/images/xiaomi-redmi-15c-4g-black.png",
  "xiaomi|redmi 15|black": "/images/xiaomi-redmi-15-black.png",
  "xiaomi|redmi a5|black": "/images/xiaomi-redmi-a5-black.png",
  "xiaomi|redmi a5|gold": "/images/xiaomi-redmi-a5-gold.png",
  "xiaomi|redmi note 12 pro 4g|grey": "/images/xiaomi-redmi-note-12-pro-4g-grey.png",
  "xiaomi|redmi note 13 pro 5g|teal": "/images/xiaomi-redmi-note-13-pro-5g-teal.png",
  "xiaomi|redmi note 14 5g|black": "/images/xiaomi-redmi-note-14-5g-black.png",
  "xiaomi|redmi note 14 5g|blue": "/images/xiaomi-redmi-note-14-5g-blue.png",
  "xiaomi|xiaomi 12 5g|grey": "/images/xiaomi-xiaomi-12-5g-grey.png",
  "xiaomi|xiaomi 12 5g|purple": "/images/xiaomi-xiaomi-12-5g-purple.png",
  "xiaomi|xiaomi 12 pro 5g|grey": "/images/xiaomi-xiaomi-12-pro-5g-grey.png",
  // === AUTO-GENERATED phone-images END ===
  // === MANUAL phone-images START (images fournies a la main) ===
  "apple|iphone 16e|black": "/images/apple-iphone-16e-black.png",
  "apple|iphone 17 pro|orange": "/images/apple-iphone-17-pro-orange.png",
  "apple|iphone 17 pro|silver": "/images/apple-iphone-17-pro-silver.png",
  "apple|iphone 17|blue": "/images/apple-iphone-17-blue.png",
  "apple|iphone 17|green": "/images/apple-iphone-17-green.png",
  "google|pixel 9 5g|black": "/images/google-pixel-9-5g-black.png",
  "google|pixel 9 pro fold 5g|black": "/images/google-pixel-9-pro-fold-5g-black.png",
  "oneplus|15 5g|black": "/images/oneplus-15-5g-black.png",
  "samsung|galaxy s23 5g|black": "/images/samsung-galaxy-s23-5g-black.png",
  "samsung|galaxy s23 5g|green": "/images/samsung-galaxy-s23-5g-green.png",
  "samsung|galaxy s23 5g|purple": "/images/samsung-galaxy-s23-5g-purple.png",
  "samsung|galaxy s23|vert": "/images/samsung-galaxy-s23-vert.png",
  "samsung|galaxy s25 5g|black": "/images/samsung-galaxy-s25-5g-black.png",
  "samsung|galaxy s25 5g|blue": "/images/samsung-galaxy-s25-5g-blue.png",
  "samsung|galaxy z flip3 5g|beige": "/images/samsung-galaxy-z-flip3-5g-beige.png",
  "samsung|galaxy z flip3 5g|purple": "/images/samsung-galaxy-z-flip3-5g-purple.png",
  "xiaomi|13 ultra 5g|white": "/images/xiaomi-13-ultra-5g-white.png",
  "xiaomi|14t 5g|black": "/images/xiaomi-14t-5g-black.png",
  "xiaomi|14t 5g|green": "/images/xiaomi-14t-5g-green.png",
  "xiaomi|17 ultra 5g|black": "/images/xiaomi-17-ultra-5g-black.png",
  "xiaomi|redmi note 12 pro 5g|black": "/images/xiaomi-redmi-note-12-pro-5g-black.png",
  "xiaomi|redmi note 12 pro 5g|blue": "/images/xiaomi-redmi-note-12-pro-5g-blue.png",
  "xiaomi|redmi note 13 5g|black": "/images/xiaomi-redmi-note-13-5g-black.png",
  "xiaomi|redmi note 13 pro 5g|black": "/images/xiaomi-redmi-note-13-pro-5g-black.png",
  "xiaomi|redmi note 14 pro 5g|black": "/images/xiaomi-redmi-note-14-pro-5g-black.png",
  "xiaomi|xiaomi 12t 5g|black": "/images/xiaomi-xiaomi-12t-5g-black.png",
  // === MANUAL phone-images END ===
};

// Build the lookup key for MODEL_IMAGES. Color is optional.
export function modelImageKey(
  brand: string,
  model: string,
  color?: string | null,
): string {
  const base = `${(brand || '').trim().toLowerCase()}|${(model || '').trim().toLowerCase()}`;
  const c = (color || '').trim().toLowerCase();
  return c ? `${base}|${c}` : base;
}
